### ISSUE TITLE
Hovering on volume bar actually lowers the volume

### ISSUE THREAD

**Issue by TheLambdaFunction** [vicr123/theshell#42] opened 2018-11-09 14:12 UTC
Hello,

I noticed that when I hover with the mouse over the volume icon, which then it transforms into the slider, it slightly lowers the volume, even without touching it. If done many time the volume gets considerably low. 

I am on Manjaro Linux (Arch) and the bar is in the _minimized mode_ .. I don't know if it's related, but when this happened I had quite a few windows open, making the bar scroll-able.

**Comment by vicr123** [comment] 2018-11-09 21:38
Hello,

Thanks for the bug report. Do you have pulseaudio installed on your computer?

**Comment by TheLambdaFunction** [comment] 2018-11-12 08:56
Hi,

No problem. Actually I do.. I also got to say that I installed theShell over a Manjaro XFCE.
I also installed it on a KDE Manjaro, and I have to check that on KDE it does not happen (in theory it works, but I never checked for it). Maybe some dependency/config missing? Because if the system has no KDE settings manager, configuring theShell it's a bit chaotic, maybe some more advanced settings need to be included

**Comment by vicr123** [comment] 2018-11-12 10:31
Hey,

Turns out I can actually reproduce the problem on my computer after opening pavucontrol and noticing that the volume control knob was moving down.

Thanks for filing this bug hahaha, I don't use the volume knob much because I have hardware keys on my keyboard :)

**Comment by vicr123** [comment] 2018-11-22 12:18
Should be fixed in the latest Blueprint now (7431b22). Thanks for filing this bug :)

**Closed as completed by vicr123** 2018-11-22 12:18 UTC
